apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
    cni:
      enabled: true
    pilot:
      k8s:
        env:
          - name: PILOT_TRACE_SAMPLING
            value: "1"
        resources:
          requests:
            cpu: 0m
            memory: 0Mi
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 0m
            memory: 0Mi
